---
- name: "DATA VIEWS: DELETE: Request (Space: {{ space_name }})"
  register: deleted_resources
  uri:
    method: DELETE
    url: "{{ kibana_endpoint }}/s/{{ space_name }}/api/data_views/data_view/{{ item.id }}"
    status_code: [ 200 ]
    body_format: json
    return_content: no
    validate_certs: no
    timeout: 300
    headers:
      Authorization: "ApiKey {{ kibana_details.api_key }}"
      kbn-xsrf: true
  with_items:
    - "{{ dv_resources_to_delete }}"
  tags:
    - kibana-data-views-run
    - kibana-data-views-debug
    - kibana-run-all
    - kibana-debug-all
