---
- name: "INTEGRATION: UPDATE: Request (Policy: {{ policy_name }})"
  register: created_resources
  uri:
    method: PUT
    url: "{{ kibana_endpoint }}/api/fleet/package_policies/{{item.id}}"
    status_code: [ 200 ]
    body_format: json
    return_content: no
    validate_certs: no
    timeout: 300
    body: "{{ kibana.agent_policies[policy_name].integrations[item.name] | combine({'policy_id': policy_name}) | combine({'name': item.name}) }}"
    headers:
      Authorization: "ApiKey {{ kibana_details.api_key }}"
      kbn-xsrf: true
  with_items:
    - "{{ resources_to_update }}"
  tags:
    - kibana-integrations-run
    - kibana-integrations-debug
    - kibana-run-all
    - kibana-debug-all