---
- name: "INTEGRATION: GET: Request (Policy: {{ policy_name }})"
  register: fetched_resources
  uri:
    method: GET
    url: "{{ kibana_endpoint }}/api/fleet/agent_policies/{{ policy_name }}"
    status_code: [ 200 ]
    body_format: json
    return_content: no
    validate_certs: no
    headers:
      Authorization: "ApiKey {{ kibana_details.api_key }}"
  tags:
    - kibana-integrations-run
    - kibana-integrations-debug
    - kibana-run-all
    - kibana-debug-all

- name: "INTEGRATION: GET: DEBUG: Request (Policy: {{ policy_name }})"
  debug:
    msg: "{{ fetched_resources.json.item.package_policies }}"
  when: fetched_resources.json is defined
  tags:
    - kibana-integrations-run
    - kibana-integrations-debug
    - kibana-run-all
    - kibana-debug-all

- name: "INTEGRATION: GET: Setup Empty Array (Policy: {{ policy_name }})"
  set_fact:
    fetched_resources_names: [ ]
  tags:
    - kibana-integrations-run
    - kibana-integrations-debug
    - kibana-run-all
    - kibana-debug-all

- name: "INTEGRATION: GET: Parse Names (Policy: {{ policy_name }})"
  set_fact:
    fetched_resources_names: "{{ fetched_resources_names | default([]) + [{'name': item.name, 'id': item.id}] }}"
  with_items: "{{ fetched_resources.json.item.package_policies }}"
  when: fetched_resources.json.item.package_policies is defined
  tags:
    - kibana-integrations-run
    - kibana-integrations-debug
    - kibana-run-all
    - kibana-debug-all

- debug:
    msg: "{{ fetched_resources_names  }}"
  tags:
    - kibana-integrations-run
    - kibana-integrations-debug
    - kibana-run-all
    - kibana-debug-all

- name: "INTEGRATION: GET: DEBUG: Parse Names (Policy: {{ policy_name }})"
  debug:
    msg: "{{ fetched_resources_names }}"
  tags:
    - kibana-integrations-debug
    - kibana-debug-all
