---
- name: "LOAD: Load Definitions"
  include_vars:
    file: "{{ resource_definitions_path }}"
  tags:
    - kibana-spaces-run
    - kibana-spaces-debug
    - kibana-data-views-run
    - kibana-data-views-debug
    - kibana-settings-run
    - kibana-settings-debug
    - kibana-run-all
    - kibana-debug-all

- name: "LOAD: DEBUG: Load Definitions"
  debug:
    msg: "{{ kibana.spaces }}"
  when: kibana.spaces is defined
  tags:
    - kibana-spaces-debug
    - kibana-data-views-debug
    - kibana-settings-debug
    - kibana-debug-all

- name: "LOAD: Setup Empty Array"
  set_fact:
    resources_names: [ ]
  tags:
    - kibana-spaces-run
    - kibana-spaces-debug
    - kibana-data-views-run
    - kibana-data-views-debug
    - kibana-settings-run
    - kibana-settings-debug
    - kibana-run-all
    - kibana-debug-all

- name: "LOAD: Parse Names"
  set_fact:
    resources_names: "{{ kibana.spaces.keys() | default([]) }}"
  when: kibana.spaces | length > 0
  tags:
    - kibana-spaces-run
    - kibana-spaces-debug
    - kibana-data-views-run
    - kibana-data-views-debug
    - kibana-settings-run
    - kibana-settings-debug
    - kibana-run-all
    - kibana-debug-all

- name: "LOAD: DEBUG: Parse Names"
  debug:
    msg: "{{ resources_names }}"
  tags:
    - kibana-spaces-debug
    - kibana-data-views-debug
    - kibana-settings-debug
    - kibana-debug-all