---
- name: "UPDATE: Request"
  register: updated_resources
  uri:
    method: PUT
    url: "{{ kibana_endpoint }}/api/security/role/{{ item }}"
    status_code: [ 204 ]
    body_format: json
    return_content: no
    validate_certs: no
    body: "{{ kibana.roles[item] }}"
    headers:
      Authorization: "ApiKey {{ kibana_details.api_key }}"
      kbn-xsrf: true
  with_items:
    - "{{ resources_to_update }}"
  tags:
    - kibana-roles-run
    - kibana-roles-debug
    - kibana-run-all
    - kibana-debug-all
